### ISSUE TITLE
What is the hardware platform

### ISSUE THREAD

**Issue by DeqingSun** [PaserTech-Hardware/SakuraKVM-VNC#2]
Which hardware should be used for this project?

**Comment by Angelic47** [comment]
Hello, we are using allwinner Socs for this project.
Currently, this project are still under developing as we have some technical problems.
Thanks for your attention!

**Comment by DeqingSun** [comment]
So it will be a VNC project similar to AURGA Viewer? That sounds great.

I know how difficult to develop on allwinner chip. Good luck. I'm interest in getting one when the project is done.

**Comment by Angelic47** [comment]
Yes most likely, but still has some different:

- The hardware is mostly like a android TV box. This will much larger than AURGA, while AURGA looks like a USB stick;
- And, thus, this project is a stand-alone device. This means, it has its own power source, not related the host machine's power status. 
- We designed it as a "remote toolbox", so there are lots of functions likes remote USB storage, remote ISO, network share... etc.
- For allwinner Socs will have at least 16ms delay. This is due to the allwinner's cedar hardware(must fill a whole frame before start encode). This is no way to solve.
- We are a opensource project. At least software, full opensource, there is no anythings hidden in the dark. 
- This also means it has a complex linux system, for now we chosed armbian. It can runs custom software, theory, if the hardware resources is enough. We also provided the ssh access for this.

We will try to solve the technical problems as soon as possible!
Thanks for your attention!
